<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Pitch Assignment</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #374151;
            background-color: #f9fafb;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }
        .header {
            background-color: #4f46e5;
            color: #ffffff;
            padding: 24px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            font-weight: 600;
        }
        .content {
            padding: 24px;
        }
        .brief-info {
            background-color: #f3f4f6;
            border-radius: 6px;
            padding: 16px;
            margin-bottom: 20px;
        }
        .brief-info h2 {
            margin: 0 0 8px 0;
            font-size: 18px;
            color: #111827;
        }
        .brief-info p {
            margin: 4px 0;
            font-size: 14px;
        }
        .label {
            font-weight: 600;
            color: #6b7280;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .confidence-badge {
            display: inline-block;
            background-color: #dbeafe;
            color: #1d4ed8;
            padding: 4px 12px;
            border-radius: 9999px;
            font-size: 14px;
            font-weight: 600;
        }
        .cta-button {
            display: inline-block;
            background-color: #4f46e5;
            color: #ffffff;
            text-decoration: none;
            padding: 12px 24px;
            border-radius: 6px;
            font-weight: 600;
            text-align: center;
            margin-top: 16px;
        }
        .cta-button:hover {
            background-color: #4338ca;
        }
        .footer {
            background-color: #f3f4f6;
            padding: 16px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎯 New Pitch Assignment</h1>
        </div>

        <div class="content">
            <p>Hello {{ $assignment->pic->name ?? 'there' }},</p>

            <p>You have been assigned to a new pitch opportunity based on AI analysis.</p>

            <div class="brief-info">
                <h2>{{ $brief->title }}</h2>
                <p><span class="label">Client:</span> {{ $brief->client_name }}</p>
                @if($brief->industry)
                    <p><span class="label">Industry:</span> {{ $brief->industry }}</p>
                @endif
                @if($brief->budget)
                    <p><span class="label">Budget:</span> ${{ number_format((float)$brief->budget, 2) }}</p>
                @endif
                @if($brief->deadline)
                    <p><span class="label">Deadline:</span> {{ \Carbon\Carbon::parse($brief->deadline)->format('M d, Y') }}</p>
                @endif
            </div>

            <p><span class="label">AI Confidence Score:</span> <span class="confidence-badge">{{ $assignment->confidence }}%</span></p>

            @if($assignment->businessUnit)
                <p><span class="label">Business Unit:</span> {{ $assignment->businessUnit->name }}</p>
            @endif

            <p style="margin-top: 24px;">
                <a href="{{ url('/briefs/' . $brief->id) }}" class="cta-button">View Brief Details</a>
            </p>

            <p style="margin-top: 24px; font-size: 14px; color: #6b7280;">
                This assignment was automatically generated by the AI analysis system based on the brief content and business unit matching.
            </p>
        </div>

        <div class="footer">
            <p>BriefGood - AI-Powered Pitch Management</p>
        </div>
    </div>
</body>
</html>
